spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: somePassword


  aop:
    proxy-target-class: true
security:
  basic:
    enabled: false
management:
  security:
    enabled: false